# Generated by Django 6.0.8 on 2026-08-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin'), ('owner', 'Owner')], default='customer', help_text='Determines control-panel access. See ROLES.md for the full matrix.', max_length=20),
        ),
    ]
