# Generated by Django 6.0.8 on 2026-08-16 17:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_at_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='10% reservation fee, computed server-side. Never taken from the client.', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('authorized', 'Reservation authorised'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
    ]
