# Generated by Django 6.0.8 on 2026-08-11 20:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifier. Generated from the name if left blank.",
                        unique=True,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price in GBP.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "range_km",
                    models.PositiveIntegerField(help_text="WLTP range in kilometres."),
                ),
                ("top_speed_kmh", models.PositiveIntegerField()),
                (
                    "acceleration_0_100",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100 km/h in seconds.",
                        max_digits=4,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="Catalog card image. 16:9 works best with the store grid.",
                        upload_to="cars/thumbnails/",
                    ),
                ),
                (
                    "thumbnail_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the thumbnail. Falls back to the car name.",
                        max_length=200,
                    ),
                ),
                (
                    "is_hero",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the model featured in the homepage cinematic sequence.",
                    ),
                ),
                (
                    "has_real_imagery",
                    models.BooleanField(
                        default=False,
                        help_text="False for models whose photography has not been shot yet -- the store renders those with a stylised placeholder treatment and a 'visualisation pending' badge rather than pretending otherwise.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "car model",
                "ordering": ("-is_hero", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lower numbers appear first in the gallery.",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.carmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
    ]
