# Generated by Django 6.0.8 on 2026-08-13 19:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal build cost in GBP. Never exposed publicly; drives profit figures.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Hidden from the public store when unticked. This is the soft-retire switch the order model asks for: a car referenced by a past order cannot be deleted (OrderItem.car is PROTECT), so it is hidden here instead. Staff still see hidden cars in the control panel.'),
        ),
    ]
