# Generated by Django 6.0.8 on 2026-08-16 16:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_cost_carmodel_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='ac_kw',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='allocation_open',
            field=models.BooleanField(default=True, help_text='When false, the store shows a waitlist instead of Add to cart.'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='battery_kwh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_style',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='charge_10_80_min',
            field=models.PositiveIntegerField(blank=True, help_text='DC 10–80% minutes.', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='country_of_build',
            field=models.CharField(default='United Kingdom', max_length=40),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='height_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='homologation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='lead_time_weeks',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='max_order_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='An allocation is one car. Raising this is a deliberate choice.'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='motor_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seats',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='service_interval',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slots_remaining',
            field=models.PositiveIntegerField(default=12, help_text='Build slots still available. Held when an order is placed, returned if it is cancelled before delivery.'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='torque_nm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='warranty_years',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paint', 'Paint'), ('interior', 'Interior'), ('wheels', 'Wheels')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to base_price. Zero is the no-cost default finish.', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cars.carmodel')),
            ],
            options={
                'ordering': ('category', 'sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('car', 'category', 'name'), name='caroption_unique_name_per_category')],
            },
        ),
    ]
